name: quickmarket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2             # Updated to the latest version
  provider: ^6.1.0         # Use a stable version that exists
  flutter_bloc: ^8.1.3     # Use a compatible version
  equatable: ^2.0.5        # Maintained, latest compatible
  firebase_core: ^3.2.0    # Updated to the latest version
  firebase_auth: ^5.1.2    # Updated to the latest version
  cloud_firestore: ^5.1.0  # Updated to the latest version
  flutter_local_notifications: ^17.2.1+2  # Updated to the latest version
  get_it: ^7.2.0           # Maintained, latest compatible
  geolocator: ^12.0.0      # Updated to the latest version
  google_maps_flutter: ^2.7.0  # Updated to the latest version
  firebase_messaging: 15.0.3  # Add this line for firebase_messaging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0    # Updated to the latest version

flutter:
  uses-material-design: true
  # Add assets or fonts if needed
  assets:
    - assets/images/  # Make sure this path matches the actual directory structure
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
